[package]
name = "ap-observability"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ap-kernel = { path = "../kernel" }
serde.workspace = true
sha2.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[lints]
workspace = true
